name: Aydin BIST Robotu

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 7-15 * * 1-5"

jobs:
  run-bist-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını al
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yükle
        run: |
          pip install yfinance pandas numpy openpyxl requests nbconvert notebook ipykernel tradingview-screener

      - name: Notebook çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          jupyter nbconvert --to notebook --execute "bist_robot.ipynb" --output "sonuc.ipynb"
