name: Aydin BIST Robotu

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  run-bist-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarini al
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yukle
        run: |
         pip install yfinance pandas numpy openpyxl requests nbconvert notebook ipykernel tradingview-screener
         python -m ipykernel install --user --name python3

      - name: Notebook calistir
        env:
         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
         CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          jupyter nbconvert --to notebook --execute "bist_robot.ipynb" --output "sonuc.ipynb"
